#index:
#    path: /
#    controller: App\Controller\DefaultController::index

user_register:
    path: /register/
    controller: App\Controller\UserController::register
user_login:
    path: /login/
    controller: App\Controller\UserController::login
user_logout:
    path: /logout/
    controller: App\Controller\UserController::logout
user_profile:
    path: /profile/
    controller: App\Controller\UserController::profile